cabinetoffice/gap-user-service

src/main/java/gov/cabinetofice/gapuserservice/config/SchedulerConfiguration.java, src/main/java/gov/cabinetofice/gapuserservice/scheduler/JwtBlacklistScheduler.java, src/main/java/gov/cabinetofice/gapuserservice/service/JwtBlacklistService.java
- Adding a missing scheduler configuration file
- Making the service method that the scheduler calls transactional so that it has access to an entity manager
=> Scheduler fix

.gitignore, pom.xml, src/main/java/gov/cabinetofice/gapuserservice/config/BeanConfig.java, src/main/java/gov/cabinetofice/gapuserservice/dto/CreateUserDto.java, src/main/java/gov/cabinetofice/gapuserservice/service/UserService.java, src/main/java/gov/cabinetofice/gapuserservice/util/HelperUtils.java, src/main/java/gov/cabinetofice/gapuserservice/utils/HelperUtils.java, src/main/java/gov/cabinetofice/gapuserservice/validation/annotations/ContainsOnlyAlphaChars.java, src/main/java/gov/cabinetofice/gapuserservice/validation/annotations/EmailAddressesMatch.java, src/main/java/gov/cabinetofice/gapuserservice/validation/annotations/PhoneNumberIsValid.java, src/main/java/gov/cabinetofice/gapuserservice/validation/validators/AlphaCharacterValidator.java, src/main/java/gov/cabinetofice/gapuserservice/validation/validators/EmailAddressMatchMatchValidator.java, src/main/java/gov/cabinetofice/gapuserservice/validation/validators/PhoneNumberValidator.java, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/main/resources/application.properties, src/main/resources/templates/register-user.html, src/test/java/gov/cabinetofice/gapuserservice/service/UserServiceTest.java, src/test/java/gov/cabinetofice/gapuserservice/util/WebUtilTest.java, src/test/java/gov/cabinetofice/gapuserservice/validation/EmailAddressMatchValidatorTest.java, src/test/java/gov/cabinetofice/gapuserservice/validation/PhoneNumberValidatorTest.java, src/test/java/gov/cabinetofice/gapuserservice/validation/validators/AlphaCharacterValidatorTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/UserControllerTest.java
- Added a user controller class 
- Added a user service class 
- Added appropriate dependencies to validate telephone numbers 
- Added validators to validate telephone numbers 
- Added necessary beans to `BeanConfig` class 
Note: this PR does not store any user information into the database. This will be done at a later date.
=> GGP-40: Register account. First pass at back end logic and tests. 

pom.xml, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/main/resources/templates/register-user.html
Fetching the CSS from govuk-frontend in a somewhat funky way, but it does the job. Rest of this PR is just standard GDS, we'll want to refactor into components potentially but for now this is fine
Looks like:
=> FGP-40: Init GDS & basic register template setup

pom.xml, src/main/java/gov/cabinetofice/gapuserservice/config/DebugProperties.java, src/main/java/gov/cabinetofice/gapuserservice/config/JwtProperties.java, src/main/java/gov/cabinetofice/gapuserservice/exceptions/UnauthorizedException.java, src/main/java/gov/cabinetofice/gapuserservice/security/JwtTokenFilter.java, src/main/java/gov/cabinetofice/gapuserservice/security/WebSecurityConfig.java, src/main/resources/application.properties, src/test/java/gov/cabinetofice/gapuserservice/security/JwtTokenFilterTest.java
- Added Spring Security to secure endpoints, unless specifically ignored
- Added debug option for local development to ignore JWT
=> FGP-63: boilerplate security with JWT auth filter

src/main/resources/db/migration/V1_2__add_token_blacklist_table.sql
Added a migration to create the token blacklist table and add an index to the jwt column on it.
=> FGP 102: Verify user service works on sandbox

src/main/java/gov/cabinetofice/gapuserservice/security/WebSecurityConfig.java
Added more paths to the security config exclusions
=> security config updates

src/main/java/gov/cabinetofice/gapuserservice/security/WebSecurityConfig.java, src/main/resources/db/migration/V1_3__add_token_blacklist_sequence.sql
- added a migration to create a missing sequence
- added the error path to the security config
=> security and database updates

.github/workflows/feature.yml, .github/workflows/pushImage.yml
Adding a temporary exception for the OSS index in dependency checker
=> Adding a temporary exception for the OSS index in dependency check

src/main/resources/db/migration/V1_3__add_cognito_user_tables.sql, src/main/resources/db/migration/V1_3__add_users_table.sq
- Adds new table to support cognito migration
Migration script is here: https://github.com/john-tco/cognito-migration/blob/test/index.ts  (no mr required but needs to be reviewed with this)
=> GAP-1847 | support cognito user migration

src/main/java/gov/cabinetofice/gapuserservice/model/User.java, src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/test/java/gov/cabinetofice/gapuserservice/model/UserTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
Adding roles & department name to JWT
=> Adding roles & department name to JWT

src/main/java/gov/cabinetofice/gapuserservice/dto/UserDto.java, src/main/java/gov/cabinetofice/gapuserservice/enums/LoginJourneyRedirect.java, src/main/java/gov/cabinetofice/gapuserservice/enums/LoginJourneyState.java, src/main/java/gov/cabinetofice/gapuserservice/model/Role.java, src/main/java/gov/cabinetofice/gapuserservice/model/RoleEnum.java, src/main/java/gov/cabinetofice/gapuserservice/model/User.java, src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/main/resources/application.properties, src/main/resources/db/migration/V1_12__insert_technical_support_role.sql, src/test/java/gov/cabinetofice/gapuserservice/model/UserTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
- Added a TECHNICAL_SUPPORT role to the enum
- Added a migration to commit this role to the database
- Updated the state enums to cater for this new role
- Updated tests
=> TMI2-178: adding technical support role

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java
=> Whitespace change

src/main/java/gov/cabinetofice/gapuserservice/model/Role.java, src/main/java/gov/cabinetofice/gapuserservice/model/User.java
=> Creating join table - fixing relationship

src/main/java/gov/cabinetofice/gapuserservice/model/User.java, src/main/resources/db/migration/V1_18__add_unique_constraints.sql
=> Adding unique constraints & fixing cascade delete

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java
=> Removing transactional annotations

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java
=> Removing transactional annotations (#111)

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/UserControllerTest.java
https://github.com/cabinetoffice/gap-user-service/assets/135323857/1e1dd66b-524c-4f26-9393-0964edcd3fe7
=> GAP-2011-Add-None-To-Department

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java
Ticket # and link: https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2079
Summary of the changes and the related issue. List any dependencies that are required for this change: Adds a missing url to the Back link on the updated email page.
=> GAP-2079:  Back link fix

src/main/java/gov/cabinetofice/gapuserservice/web/controlleradvice/ControllerExceptionHandler.java
=> fix(exception-handling): fixes generic exception handler to throw

src/main/java/gov/cabinetofice/gapuserservice/enums/LoginJourneyState.java
=> Fixing privacy policy workaround

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
Fixes issue where redirect url was being overridden in privacy policy.  Previously the url was retrieved from a redirect url cookie.  this has been moved to the state cookie.
https://technologyprogramme.atlassian.net/browse/GAP-1974
=> fix(redirect-url): fixes redirect url being overridden in privacy policy

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/main/resources/application.properties, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
Makes cookie domain configurable
https://eu-west-2.console.aws.amazon.com/codesuite/codecommit/repositories/GAP-infra/pull-requests/122/changes?region=eu-west-2
=> fix(cookie-domain): makes cookie domain configurable

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
Attempting to share our jwt cookie across the apply/find domains as per:
https://jaygould.co.uk/2021-08-20-sharing-cookies-jwt-between-different-domains/#:~:text=Cookies%20aren't%20shared%20between,this%20situation%20are%20fairly%20clear
=> Test sharing a cookie across domains via CORS

.github/workflows/promoteToProd.yml, .github/workflows/pushImage.yml
Simultaneously creates docker image, and tests app. Deploys docker image of both stages pass.
- Upgrading login to ecr to v2 which solves a security issue
=> Improving CD pipelines workflow

src/main/java/gov/cabinetofice/gapuserservice/enums/LoginJourneyRedirect.java, src/main/java/gov/cabinetofice/gapuserservice/util/EncodeURIComponent.java, src/test/java/gov/cabinetofice/gapuserservice/util/EncodeURIComponentTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
related prs:
- https://github.com/cabinetoffice/gap-find-apply-web/pull/121
- https://github.com/cabinetoffice/gap-find-web/pull/58
returns apply & find migration status for admins
=> Return find and apply migration status for admins

src/main/java/gov/cabinetofice/gapuserservice/dto/SuperAdminDashboardPageDto.java, src/main/java/gov/cabinetofice/gapuserservice/dto/UserAndRelationsDto.java, src/main/java/gov/cabinetofice/gapuserservice/dto/UserDto.java, src/main/java/gov/cabinetofice/gapuserservice/repository/RoleRepository.java, src/main/java/gov/cabinetofice/gapuserservice/repository/UserRepository.java, src/main/java/gov/cabinetofice/gapuserservice/security/JwtTokenFilter.java, src/main/java/gov/cabinetofice/gapuserservice/security/WebSecurityConfig.java, src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/main/java/gov/cabinetofice/gapuserservice/web/SuperAdminController.java, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/test/java/gov/cabinetofice/gapuserservice/security/JwtTokenFilterTest.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/SuperAdminControllerTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/UserControllerTest.java
Adds endpoints to user service that allows a super admin to retrieve the necessary values to initiate a transfer in grant ownership.
Moves auth to a more granular approach for each user role.
Ticket # and link : [GAP-1784](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-1784)
Adds a new endpoint to the UserController.
Adds a supporting repository method.
Granular auth approach.
Has no functional dependence on other PRs as controller method is only invoked on new pages.
-  [x] Unit Test …
=> GAP-1784: Transfer Grant Ownership

src/main/java/gov/cabinetofice/gapuserservice/security/WebSecurityConfig.java, src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
=> adds logout path to security whitelist

src/main/java/gov/cabinetofice/gapuserservice/security/WebSecurityConfig.java, src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
=> Merging develop into release branch

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
- adds call to find to delete user
- extracts existing call to apply out to another method for readability 
https://technologyprogramme.atlassian.net/browse/GAP-2306
Linked PRs:
[Adds delete user endpoint by sub or email by dylanwrightCO · Pull Request #96 · cabinetoffice/gap-find-web](https://github.com/cabinetoffice/gap-find-web/pull/96) 
[Adds delete function by sub and email by dylanwrightCO · Pull Request #76 · cabinetoffice/gap-find-backend](https://github.com/cabinetoffice/gap-find-backend/pull/76) 
Full screen recording on ticket
=> Adds call to delete find user by sub or email

pom.xml, src/main/java/gov/cabinetofice/gapuserservice/config/BeanConfig.java, src/main/java/gov/cabinetofice/gapuserservice/config/SpotlightConfig.java, src/main/java/gov/cabinetofice/gapuserservice/enums/SpotlightOAuthAuditEvent.java, src/main/java/gov/cabinetofice/gapuserservice/enums/SpotlightOAuthAuditStatus.java, src/main/java/gov/cabinetofice/gapuserservice/enums/SpotlightOAuthAuditType.java, src/main/java/gov/cabinetofice/gapuserservice/exceptions/SpotlightInvalidStateException.java, src/main/java/gov/cabinetofice/gapuserservice/model/SpotlightOAuthAudit.java, src/main/java/gov/cabinetofice/gapuserservice/repository/SpotlightOAuthAuditRepository.java, src/main/java/gov/cabinetofice/gapuserservice/service/SpotlightService.java, src/main/java/gov/cabinetofice/gapuserservice/web/SpotlightController.java, src/main/resources/application.properties, src/main/resources/db/migration/V1_22__add_spotlight_oauth_audit_table.sql, src/test/java/gov/cabinetofice/gapuserservice/service/SpotlightServiceTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/SpotlightControllerTest.java
https://technologyprogramme.atlassian.net/browse/TMI2-445
Spotlight OAuth implementation
=> TMI2-445: Spotlight OAuth

src/main/java/gov/cabinetofice/gapuserservice/dto/SpotlightIntegrationAuditDto.java, src/main/java/gov/cabinetofice/gapuserservice/repository/SpotlightOAuthAuditRepository.java, src/main/java/gov/cabinetofice/gapuserservice/service/SpotlightService.java, src/main/java/gov/cabinetofice/gapuserservice/web/SpotlightController.java, src/test/java/gov/cabinetofice/gapuserservice/service/SpotlightServiceTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/SpotlightControllerTest.java
https://technologyprogramme.atlassian.net/jira/software/projects/TMI2/boards/331?selectedIssue=TMI2-447
adds an endpoint for the fe to consume
related pr: https://github.com/cabinetoffice/gap-find-apply-web/pull/180
=> TMI2-447: Super-admin Integrations api

src/main/java/gov/cabinetofice/gapuserservice/enums/SpotlightOAuthAuditEvent.java, src/main/java/gov/cabinetofice/gapuserservice/exceptions/SpotlightTokenException.java, src/main/java/gov/cabinetofice/gapuserservice/scheduler/SpotlightOAuthRefreshScheduler.java, src/main/java/gov/cabinetofice/gapuserservice/service/SpotlightService.java, src/main/java/gov/cabinetofice/gapuserservice/web/SpotlightController.java, src/main/resources/application.properties, src/test/java/gov/cabinetofice/gapuserservice/scheduler/SpotlightOAuthRefreshSchedulerTest.java, src/test/java/gov/cabinetofice/gapuserservice/service/SpotlightServiceTest.java, src/test/java/gov/cabinetofice/gapuserservice/web/SpotlightControllerTest.java
https://technologyprogramme.atlassian.net/browse/TMI2-446
Scheduled job to refresh the Spotlight Access token
=> TMI2-446: Spotlight token refresh

src/main/java/gov/cabinetofice/gapuserservice/dto/UpdateFundingOrgDto.java, src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
https://technologyprogramme.atlassian.net/browse/TMI2-474
Updates funding org in apply when a users department is changed
=> Updates funding org when department is changed

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java
Modifies uri to delete user from apply
https://technologyprogramme.atlassian.net/browse/TMI2-476
=> modifying uri to delete user deps

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
=> Handle 404 from apply app for super admin journeys

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
* Handle 404 from apply app for super admin journeys ---------
=> Handle 404 from apply app for super admin journeys (#164)

src/main/java/gov/cabinetofice/gapuserservice/dto/ChangeDepartmentDto.java, src/main/java/gov/cabinetofice/gapuserservice/validation/annotations/FieldNotNull.java, src/main/java/gov/cabinetofice/gapuserservice/validation/validators/NullFieldValidator.java, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/test/java/gov/cabinetofice/gapuserservice/web/UserControllerTest.java
Ticket GAP-2072: https://technologyprogramme.atlassian.net/browse/GAP-2072
Added custom annotation and implemented this in UserController to prevent a null value for Department selection.
=> Added custom annotation and implemented this in UserController to pre

src/main/resources/templates/privacy-policy.html
Ticket [GAP-2378](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2378)
- Removing label wrapper regression
[GAP-2378]: https://technologyprogramme.atlassian.net/browse/GAP-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2378: Fixing privacy policy

.github/workflows/promoteToProd.yml, .github/workflows/pushImage.yml
Changes to actions. Adding secret to repository.
=> Running actions as aws role

src/main/java/gov/cabinetofice/gapuserservice/dto/CreateTechSupportUserDto.java, src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
=> Updates createtechSupportUserDto to have department name

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
=> Adds check for null department when changing tech support user role

src/main/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2.java, src/test/java/gov/cabinetofice/gapuserservice/web/LoginControllerV2Test.java
[TMI2-559 - Error shown on back press after logging in via One Login to sign up for updates](https://technologyprogramme.atlassian.net/browse/TMI2-559)
Added logic to check if user is logged in and redirects as appropriate if they go Back on the browser after logging in. Will need to be tested in sandbox/QA to properly verify fix due to how OneLogin is mocked in local dev. 
=> TMI2-559 - Added logic to check if user is logged in, fixed tests.

src/main/java/gov/cabinetofice/gapuserservice/dto/UserSubsRequestDto.java, src/main/java/gov/cabinetofice/gapuserservice/web/UserController.java, src/test/java/gov/cabinetofice/gapuserservice/web/UserControllerTest.java
https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2140
Adds an endpoint for admin-service to retrieve emails from
=> GAP-2140: Adds endpoint to get user emails from subs

src/main/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetofice/gapuserservice/service/user/OneLoginUserServiceTest.java
=> Handles removing admin role

src/main/java/gov/cabinetofice/gapuserservice/security/JwtTokenFilter.java, src/test/java/gov/cabinetofice/gapuserservice/security/JwtTokenFilterTest.java
=> fixes issue when locally developing and ignore debug property is true

src/main/java/gov/cabinetofice/gapuserservice/dto/UserRolesJwtResponse.java, src/main/java/gov/cabinetofice/gapuserservice/web/RoleController.java
Small change to add the isTechnicalSupport functionality to the jwt response dto
=> GAP-2490: Bypass One Login

src/main/java/gov/cabinetofice/gapuserservice/service/jwt/impl/CustomJwtServiceImpl.java
=> re-adds jti value as required for event service logging

src/main/java/gov/cabinetofice/gapuserservice/service/jwt/impl/CustomJwtServiceImpl.java
Tested following all eventually redirects back to the same page:
- Reuses JWT if not expired and expiry is > 30 minutes away
- Hits refresh token if JWT is not expired & expiry is < 30 minutes away
- Hits login if JWT is expired
=> GAP-2489: Checks for JWT expiry in isValid

src/main/java/gov/cabinetoffice/gapuserservice/web/LoginController.java
Need 307s to preserve post requests and forward them onwards when refreshing JWTs
=> GAP-2596: Refresh JWT with a POST request

src/test/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2Test.java
=> GAP-2587 | fix test params

src/main/java/gov/cabinetoffice/gapuserservice/service/user/OneLoginUserService.java, src/test/java/gov/cabinetoffice/gapuserservice/service/user/OneLoginUserServiceTest.java
use cola sub as fallback if sub doesn't exist when removing admin references
[GAP-2606](https://technologyprogramme.atlassian.net/browse/GAP-2606)
[GAP-2606]: https://technologyprogramme.atlassian.net/browse/GAP-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GAP-2606: Fix - Cant change role, block or delete COLA only users

src/main/java/gov/cabinetoffice/gapuserservice/model/SpotlightOAuthState.java, src/main/java/gov/cabinetoffice/gapuserservice/repository/SpotlightOAuthStateRepository.java, src/main/java/gov/cabinetoffice/gapuserservice/service/SpotlightService.java, src/main/resources/db/migration/V1_23__add_spotlight_state_table.sql, src/test/java/gov/cabinetoffice/gapuserservice/service/SpotlightServiceTest.java
=> store spotlight oauth state value in db

src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
=> delete duplicate jwt cookie if present

src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
=> always delete invalid user-service-token

src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
=> delete duplicate token if present

src/main/java/gov/cabinetoffice/gapuserservice/service/user/OneLoginUserService.java
=> fix token deletion on logout

src/main/java/gov/cabinetoffice/gapuserservice/web/LoginController.java
=> fix refresh-token

src/main/java/gov/cabinetoffice/gapuserservice/web/LoginController.java
=> fix refresh-token (#217)

src/main/java/gov/cabinetoffice/gapuserservice/service/OneLoginService.java, src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
=> additional logging for one login issue

src/main/java/gov/cabinetoffice/gapuserservice/service/OneLoginService.java, src/main/java/gov/cabinetoffice/gapuserservice/service/jwt/impl/CustomJwtServiceImpl.java, src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
=> Lss 728 fs support

src/main/java/gov/cabinetoffice/gapuserservice/service/OneLoginService.java, src/main/java/gov/cabinetoffice/gapuserservice/service/jwt/impl/CustomJwtServiceImpl.java, src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
* additional logging for one login issue
* logs in login method added
* logs in login method added
* additional logs and test issue fix
=> Lss 728 fs support (#220)

src/main/java/gov/cabinetoffice/gapuserservice/dto/IdTokenDto.java, src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
* additional logging for one login issue
* logs in login method added
* logs in login method added
* additional logs and test issue fix
* logs in login method added
* logs in login method added
* auth_time attribute added to fix one login issue
=> Lss 728 fs support (#222)

src/main/java/gov/cabinetoffice/gapuserservice/dto/IdTokenDto.java, src/main/java/gov/cabinetoffice/gapuserservice/service/OneLoginService.java, src/main/java/gov/cabinetoffice/gapuserservice/web/LoginControllerV2.java
=> one login issue fix
